server:
  port: 8089

spring:
  main:
    allow-bean-definition-overriding: true
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/pico_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul& characterEncoding=utf8"
    username : root
    password : TIGER

  jwt:
    secret: govlepel@$&
  jpa :
    show-sql : true
    hibernate :
      ddl-auto : update
#      ddl-auto : create
    properties :
      hibernate :
        format_sql : true
    generate-ddl : true
    database : mysql
    database-patform : org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: local
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: false
      add-properties: false

  #  main:
#    allow-bean-definition-overriding: true
  freemarker:
    cache: false
#  thymeleaf :
#    cache : false
#    enabled : true
#    prefix : classpath:/templates/
#    suffix : .html

  #spring.profiles.include=oauth
#spring:
#
#  profiles:
#    active: local
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: false
#    add-properties: false
#
#  freemarker:
#    cache: false
#
#  jwt:
#    secret: govlepel@$&
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #      show_sql: true
#        format_sql: true
##        이슈 작성할 것 - 이미 정의된 Bean Overriding이 먹히지 않을때 사용
#  main:
#    allow-bean-definition-overriding: true
#server:
#  port: 80

#spring:
#
#  profiles:
#    active: local
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: false
#    add-properties: false
#
#  freemarker:
#    cache: false
#
#  jwt:
#    secret: govlepel@$&
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #      show_sql: true
#        format_sql: true
#  #        이슈 작성할 것 - 이미 정의된 Bean Overriding이 먹히지 않을때 사용
#  main:
#    allow-bean-definition-overriding: true
#server:
#  port: 80
